{{- if .Values.k8sAuthorization.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "xct.fullname" . }}-rolebinding
  labels:
    app.kubernetes.io/name: {{ include "xct.name" . }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ include "xct.chart" $ }}
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: {{ .Values.deployment.serviceAccountName | default "default" }}
roleRef:
  kind: Role
  name: {{ include "xct.fullname" . }}-role # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
{{- end }}
