{{- if .Values.deployment.service.nodePort }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-app.fullname" . }}-service-np
  labels:
    app.kubernetes.io/name: {{ include "test-app.name" . }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ include "test-app.chart" $ }}
    {{- with .Values.deployment.labels }}
    {{ toYaml . | nindent 4 | trim -}}
    {{- end }}
  annotations:
    sidecar.istio.io/inject: "false"
    {{- with .Values.deployment.service.annotations }}
    {{ toYaml . | nindent 4 | trim -}}
    {{- end }}
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: {{ include "test-app.name" . }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
  ports:
    {{- if .Values.deployment.service.nodePort.https }}
    - name: https
      protocol: TCP
      port: 9443
      nodePort: {{ .Values.deployment.service.nodePort.https | default 9443 }}
    {{- end }}
    {{- if .Values.deployment.service.nodePort.http }}
    - name: http
      protocol: TCP
      port: 9080
      nodePort: {{ .Values.deployment.service.nodePort.http | default 8080 }}
    {{- end }}
    {{- if .Values.deployment.service.nodePort.ssh }}
    - name: ssh
      port: 22
      nodePort: {{ .Values.deployment.service.nodePort.ssh | default 9122 }}
    {{- end }}
{{- end }}
