{{- if .Values.secrets.enabled }}
# Secrets for open liberty configuration extension (bootstrap.extension.properties)
apiVersion: v1
kind: Secret
metadata:
  name: xct-secrets
  labels:
    app.kubernetes.io/name: {{ include "opf-dev-chart.name" . }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ include "opf-dev-chart.chart" $ }}
type: Opaque
stringData:
  opf-secrets : |-
    mq.fromswiftqcf.username = {{ .Values.secrets.opf.messaging.FromSWIFTQCF.username | default .Values.secrets.opf.messaging.mq.username }}
    mq.fromswiftqcf.password = {{ .Values.secrets.opf.messaging.FromSWIFTQCF.password | default .Values.secrets.opf.messaging.mq.password }}

    mq.fromswiftqcf.ssl.keystore.password={{ .Values.secrets.opf.messaging.FromSWIFTQCF.ssl.sslKeystorePassword | default .Values.secrets.opf.tls.keystore.password }}
    mq.fromswiftqcf.ssl.truststore.password={{ .Values.secrets.opf.messaging.FromSWIFTQCF.ssl.sslTruststorePassword | default .Values.secrets.opf.tls.truststore.password }}
    
    mq.receiptqcf.username = {{ .Values.secrets.opf.messaging.ReceiptQCF.username | default .Values.secrets.opf.messaging.mq.username }}
    mq.receiptqcf.password = {{ .Values.secrets.opf.messaging.ReceiptQCF.password | default .Values.secrets.opf.messaging.mq.password }}

    mq.receiptqcf.ssl.keystore.password={{ .Values.secrets.opf.messaging.ReceiptQCF.ssl.sslKeystorePassword | default .Values.secrets.opf.tls.keystore.password }}
    mq.receiptqcf.ssl.truststore.password={{ .Values.secrets.opf.messaging.ReceiptQCF.ssl.sslTruststorePassword | default .Values.secrets.opf.tls.truststore.password }}

    {{- with .Values.secrets.opf.externalSystems }}
    {{- if .fsis }}
    auth.fsis.username = {{ .fsis.username }}
    auth.fsis.password = {{ .fsis.password }}
    {{- end }}
    {{- if .xctFxs }}
    auth.fxs.username = {{ .xctFxs.username }}
    auth.fxs.password = {{ .xctFxs.password }}
    {{- end }}
    {{- if .xctGpiCct }}
    auth.gpicct.username = {{ .xctGpiCct.username }}
    auth.gpicct.password = {{ .xctGpiCct.password }}
    {{- end }}
    {{- if .xctGpiCov }}
    auth.gpicov.username = {{ .xctGpiCov.username }}
    auth.gpicov.password = {{ .xctGpiCov.password }}
    {{- end }}
    {{- if .xctGpiFit }}
    auth.gpifit.username = {{ .xctGpiFit.username }}
    auth.gpifit.password = {{ .xctGpiFit.password }}
    {{- end }}
    {{- if .xctGpiUcon }}
    auth.gpiucon.username = {{ .xctGpiUcon.username }}
    auth.gpiucon.password = {{ .xctGpiUcon.password }}
    {{- end }}
    {{- if .xctGpiGct }}
    auth.xctGpiGct.username = {{ .xctGpiGct.username }}
    auth.xctGpiGct.password = {{ .xctGpiGct.password }}
    {{- end }}
    {{- if .xctSwiftMicrogateway }}
    auth.xctSwiftMicrogateway.busAppName = {{ .xctSwiftMicrogateway.busAppName }}
    auth.xctSwiftMicrogateway.profileId = {{ .xctSwiftMicrogateway.profileId }}
    auth.xctSwiftMicrogateway.sharedKey  = {{ .xctSwiftMicrogateway.sharedKey }}
    {{- end }}
    {{- if .xctPcs }}
    auth.pcs.username = {{ .xctPcs.username }}
    auth.pcs.password = {{ .xctPcs.password }}
    {{- end }}
    {{- if .POM }}
    auth.POM.username = {{ .POM.username }}
    auth.POM.password = {{ .POM.password }}
    {{- end }}
    {{- if .nacas }}
    auth.nacas.username = {{ .nacas.username }}
    auth.nacas.password = {{ .nacas.password }}
    {{- end }}
    {{- end }}
{{- end }}