from jboss_utils import CLIHelper, OverridableConfigParser

cli = CLIHelper()
environment = OverridableConfigParser('environment.ini')

sys_props = {
    'com.clear2pay.opf.jndi.ejb31': 'true',
    'com.clear2pay.bph.opfcommon.bpel.workflow.BPEL': 'false',
    'com.clear2pay.opf.security.domain': 'opf-domain',
    'com.clear2pay.opf.security.qcfuser.name': environment.get('MDBActivationSpecs', 'qcfuser_name'),
    'com.clear2pay.opf.security.qcfuser.password': environment.get('MDBActivationSpecs', 'qcfuser_password'),
    'jms.queue.connection.factory': 'java:jboss/jms/qcf',
    'jmx.mxbean.multiname': 'true',
    'cbis.rest.base.url': environment.get('URLS', 'cbis'),
    'jms.simulator.base.url': environment.get('URLS', 'jms'),
    'sanctions.check.rest.base.url': environment.get('URLS', 'sanctions'),
    'com.clear2pay.opfpayment.fsis.riskassessment.rest.base.url': environment.get('URLS', 'fsis'),
    'com.clear2pay.opfpayment.charges.pcs.utilityservices.rest.base.url': environment.get('URLS', 'pcs'),
    'com.clear2pay.opfpayment.nacas.utilityservices.rest.base.url': environment.get('URLS', 'nacas'),
    'payment.upload.push.rest.base.url': environment.get('URLS', 'push'),
    'universal.execution.callback.rest.base.url': environment.get('URLS', 'uecr'),
    'universal.execution.rest.base.url': environment.get('URLS', 'uecr'),
    'com.clear2pay.opf.api.client.base.url.POM': environment.get('URLS', 'uecr'),
    'com.clear2pay.opf.api.client.base.url.CHANNELS': environment.get('URLS', 'uecr'),
    'client.api.support.mode': 'true',
    'bpmn.test.outputDirectory': '/tmp/bpmn',
    'com.clear2pay.bph.opf.version.color' :environment.get('MYCOLOR', 'mycolor'),

    # OVA
    'com.clear2pay.ova.opf.client.api.basic.authentication': 'false',
    'com.clear2pay.ova.security.profile': 'JBOSS_SECURITY',
    'com.clear2pay.ova.ui.slave.mode': 'false',
    'com.clear2pay.ova.opf.client.api.url': environment.get('URLS', 'rest'),
    'com.clear2pay.ova.opf.client.webtarget.read.timout': '60000',
    'com.clear2pay.ova.opf.client.webtarget.connect.timout': '30000',
    'com.clear2pay.ova.opf.authentication.enricher.cookie.name': 'JSESSIONIDSSO',
    'com.clear2pay.ova.bankingEntities.contextmode': 'ALLOW_ALL',
    'com.clear2pay.ova.banks.contextmode': 'FORCE_ALL',

    # SHARPY
    'spring.profiles.active': 'jboss',

    # Cache Relay
    'com.clear2pay.opf.relay.cache.data.change.notification.batch.mode.sync': 'True',

    # SSO
    'sso.valve.class': 'org.apache.catalina.authenticator.SingleSignOn',
    'com.sun.identity.authentication.setCookieToAllDomains': 'true',
    'com.clear2pay.bph.messageContextPersistenceEnabled': 'on',
    
    # OPFCommon MDBS
    'com.clear2pay.opf.mdb.activationSpec.DataImportServiceMDBBean.qcfuser.name': environment.get('MDBActivationSpecs', 'qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.DataImportServiceMDBBean.qcfuser.password': environment.get('MDBActivationSpecs', 'qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.DataImportServiceMDBBean.maxPoolDepth': '5',
    'com.clear2pay.opf.mdb.activationSpec.DataImportServiceMDBBean.hostName': environment.get('MDBActivationSpecs', 'qcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.DataImportServiceMDBBean.port': environment.get('MDBActivationSpecs', 'qcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.DataImportServiceMDBBean.channel': environment.get('MDBActivationSpecs', 'qcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.DataImportServiceMDBBean.transportType': environment.get('MDBActivationSpecs', 'qcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.DataImportServiceMDBBean.queueManager': environment.get('MDBActivationSpecs', 'qcf_queueManager'),
    'com.clear2pay.opf.mdb.activationSpec.TechExceptionRetryMDB.qcfuser.name': environment.get('MDBActivationSpecs', 'myqcf_qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.TechExceptionRetryMDB.qcfuser.password': environment.get('MDBActivationSpecs', 'myqcf_qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.TechExceptionRetryMDB.maxPoolDepth': '5',
    'com.clear2pay.opf.mdb.activationSpec.TechExceptionRetryMDB.hostName': environment.get('MDBActivationSpecs', 'myqcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.TechExceptionRetryMDB.port': environment.get('MDBActivationSpecs', 'myqcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.TechExceptionRetryMDB.channel': environment.get('MDBActivationSpecs', 'myqcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.TechExceptionRetryMDB.transportType': environment.get('MDBActivationSpecs', 'myqcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.TechExceptionRetryMDB.queueManager': environment.get('MDBActivationSpecs', 'myqcf_queueManager'),
    'com.clear2pay.opf.mdb.activationSpec.EventInitiationMDBBean.qcfuser.name': environment.get('MDBActivationSpecs', 'qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.EventInitiationMDBBean.qcfuser.password': environment.get('MDBActivationSpecs', 'qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.EventInitiationMDBBean.maxPoolDepth': '5',
    'com.clear2pay.opf.mdb.activationSpec.EventInitiationMDBBean.hostName': environment.get('MDBActivationSpecs', 'qcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.EventInitiationMDBBean.port': environment.get('MDBActivationSpecs', 'qcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.EventInitiationMDBBean.channel': environment.get('MDBActivationSpecs', 'qcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.EventInitiationMDBBean.transportType': environment.get('MDBActivationSpecs', 'qcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.EventInitiationMDBBean.queueManager': environment.get('MDBActivationSpecs', 'qcf_queueManager'),
    'com.clear2pay.opf.mdb.activationSpec.KafkaIntermediateEventSenderMDBBean.qcfuser.name': environment.get('MDBActivationSpecs', 'qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.KafkaIntermediateEventSenderMDBBean.qcfuser.password': environment.get('MDBActivationSpecs', 'qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.KafkaIntermediateEventSenderMDBBean.maxPoolDepth': '5',
    'com.clear2pay.opf.mdb.activationSpec.KafkaIntermediateEventSenderMDBBean.hostName': environment.get('MDBActivationSpecs', 'qcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.KafkaIntermediateEventSenderMDBBean.port': environment.get('MDBActivationSpecs', 'qcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.KafkaIntermediateEventSenderMDBBean.channel': environment.get('MDBActivationSpecs', 'qcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.KafkaIntermediateEventSenderMDBBean.transportType': environment.get('MDBActivationSpecs', 'qcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.KafkaIntermediateEventSenderMDBBean.queueManager': environment.get('MDBActivationSpecs', 'qcf_queueManager'),
    
    #OPFPayment MDBs
    'com.clear2pay.opf.mdb.activationSpec.AccountPostingServiceMDBBean.qcfuser.name': environment.get('MDBActivationSpecs', 'qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.AccountPostingServiceMDBBean.qcfuser.password': environment.get('MDBActivationSpecs', 'qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.AccountPostingServiceMDBBean.maxPoolDepth': '20',
    'com.clear2pay.opf.mdb.activationSpec.AccountPostingServiceMDBBean.hostName': environment.get('MDBActivationSpecs', 'qcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.AccountPostingServiceMDBBean.port': environment.get('MDBActivationSpecs', 'qcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.AccountPostingServiceMDBBean.channel': environment.get('MDBActivationSpecs', 'qcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.AccountPostingServiceMDBBean.transportType': environment.get('MDBActivationSpecs', 'qcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.AccountPostingServiceMDBBean.queueManager': environment.get('MDBActivationSpecs', 'qcf_queueManager'),
    'com.clear2pay.opf.mdb.activationSpec.AsyncBPELInvoker.qcfuser.name': environment.get('MDBActivationSpecs', 'myqcf_qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.AsyncBPELInvoker.qcfuser.password': environment.get('MDBActivationSpecs', 'myqcf_qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.AsyncBPELInvoker.maxPoolDepth': '20',
    'com.clear2pay.opf.mdb.activationSpec.AsyncBPELInvoker.hostName': environment.get('MDBActivationSpecs', 'myqcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.AsyncBPELInvoker.port': environment.get('MDBActivationSpecs', 'myqcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.AsyncBPELInvoker.channel': environment.get('MDBActivationSpecs', 'myqcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.AsyncBPELInvoker.transportType': environment.get('MDBActivationSpecs', 'myqcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.AsyncBPELInvoker.queueManager': environment.get('MDBActivationSpecs', 'myqcf_queueManager'),
    'com.clear2pay.opf.mdb.activationSpec.BillingServiceMDB.qcfuser.name': environment.get('MDBActivationSpecs', 'qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.BillingServiceMDB.qcfuser.password': environment.get('MDBActivationSpecs', 'qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.BillingServiceMDB.maxPoolDepth': '20',
    'com.clear2pay.opf.mdb.activationSpec.BillingServiceMDB.hostName': environment.get('MDBActivationSpecs', 'qcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.BillingServiceMDB.port': environment.get('MDBActivationSpecs', 'qcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.BillingServiceMDB.channel': environment.get('MDBActivationSpecs', 'qcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.BillingServiceMDB.transportType': environment.get('MDBActivationSpecs', 'qcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.BillingServiceMDB.queueManager': environment.get('MDBActivationSpecs', 'qcf_queueManager'),
    'com.clear2pay.opf.mdb.activationSpec.Urgency1AsyncBPELInvoker.qcfuser.name': environment.get('MDBActivationSpecs', 'myqcf_qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.Urgency1AsyncBPELInvoker.qcfuser.password': environment.get('MDBActivationSpecs', 'myqcf_qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.Urgency1AsyncBPELInvoker.maxPoolDepth': '20',
    'com.clear2pay.opf.mdb.activationSpec.Urgency1AsyncBPELInvoker.hostName': environment.get('MDBActivationSpecs', 'myqcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.Urgency1AsyncBPELInvoker.port': environment.get('MDBActivationSpecs', 'myqcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.Urgency1AsyncBPELInvoker.channel': environment.get('MDBActivationSpecs', 'myqcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.Urgency1AsyncBPELInvoker.transportType': environment.get('MDBActivationSpecs', 'myqcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.Urgency1AsyncBPELInvoker.queueManager': environment.get('MDBActivationSpecs', 'myqcf_queueManager'),
    'com.clear2pay.opf.mdb.activationSpec.NotificationServiceMDB.qcfuser.name': environment.get('MDBActivationSpecs', 'myqcf_qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.NotificationServiceMDB.qcfuser.password': environment.get('MDBActivationSpecs', 'myqcf_qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.NotificationServiceMDB.maxPoolDepth': '5',
    'com.clear2pay.opf.mdb.activationSpec.NotificationServiceMDB.hostName': environment.get('MDBActivationSpecs', 'myqcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.NotificationServiceMDB.port': environment.get('MDBActivationSpecs', 'myqcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.NotificationServiceMDB.channel': environment.get('MDBActivationSpecs', 'myqcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.NotificationServiceMDB.transportType': environment.get('MDBActivationSpecs', 'myqcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.NotificationServiceMDB.queueManager': environment.get('MDBActivationSpecs', 'myqcf_queueManager'),
    'com.clear2pay.opf.mdb.activationSpec.SubmissionServiceMDB.qcfuser.name': environment.get('MDBActivationSpecs', 'qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.SubmissionServiceMDB.qcfuser.password': environment.get('MDBActivationSpecs', 'qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.SubmissionServiceMDB.maxPoolDepth': '5',
    'com.clear2pay.opf.mdb.activationSpec.SubmissionServiceMDB.hostName': environment.get('MDBActivationSpecs', 'qcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.SubmissionServiceMDB.port': environment.get('MDBActivationSpecs', 'qcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.SubmissionServiceMDB.channel': environment.get('MDBActivationSpecs', 'qcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.SubmissionServiceMDB.transportType': environment.get('MDBActivationSpecs', 'qcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.SubmissionServiceMDB.queueManager': environment.get('MDBActivationSpecs', 'qcf_queueManager'),
    'com.clear2pay.opf.mdb.activationSpec.TimeoutReceiptHandlingMDB.qcfuser.name': environment.get('MDBActivationSpecs', 'myqcf_qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.TimeoutReceiptHandlingMDB.qcfuser.password': environment.get('MDBActivationSpecs', 'myqcf_qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.TimeoutReceiptHandlingMDB.maxPoolDepth': '5',
    'com.clear2pay.opf.mdb.activationSpec.TimeoutReceiptHandlingMDB.hostName': environment.get('MDBActivationSpecs', 'myqcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.TimeoutReceiptHandlingMDB.port': environment.get('MDBActivationSpecs', 'myqcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.TimeoutReceiptHandlingMDB.channel': environment.get('MDBActivationSpecs', 'myqcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.TimeoutReceiptHandlingMDB.transportType': environment.get('MDBActivationSpecs', 'myqcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.TimeoutReceiptHandlingMDB.queueManager': environment.get('MDBActivationSpecs', 'myqcf_queueManager'),
    'com.clear2pay.opf.mdb.activationSpec.WarehousingServiceMDB.qcfuser.name': environment.get('MDBActivationSpecs', 'qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.WarehousingServiceMDB.qcfuser.password': environment.get('MDBActivationSpecs', 'qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.WarehousingServiceMDB.maxPoolDepth': '5',
    'com.clear2pay.opf.mdb.activationSpec.WarehousingServiceMDB.hostName': environment.get('MDBActivationSpecs', 'qcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.WarehousingServiceMDB.port': environment.get('MDBActivationSpecs', 'qcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.WarehousingServiceMDB.channel': environment.get('MDBActivationSpecs', 'qcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.WarehousingServiceMDB.transportType': environment.get('MDBActivationSpecs', 'qcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.WarehousingServiceMDB.queueManager': environment.get('MDBActivationSpecs', 'qcf_queueManager'),
    'com.clear2pay.opf.mdb.activationSpec.SAFRestPaymentUploadMDB.qcfuser.name': environment.get('MDBActivationSpecs', 'qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.SAFRestPaymentUploadMDB.qcfuser.password': environment.get('MDBActivationSpecs', 'qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.SAFRestPaymentUploadMDB.maxPoolDepth': '20',
    'com.clear2pay.opf.mdb.activationSpec.SAFRestPaymentUploadMDB.hostName': environment.get('MDBActivationSpecs', 'qcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.SAFRestPaymentUploadMDB.port': environment.get('MDBActivationSpecs', 'qcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.SAFRestPaymentUploadMDB.channel': environment.get('MDBActivationSpecs', 'qcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.SAFRestPaymentUploadMDB.transportType': environment.get('MDBActivationSpecs', 'qcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.SAFRestPaymentUploadMDB.queueManager': environment.get('MDBActivationSpecs', 'qcf_queueManager'),
    'com.clear2pay.opf.mdb.activationSpec.InterchangeLoaderMDB.qcfuser.name': environment.get('MDBActivationSpecs', 'qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.InterchangeLoaderMDB.qcfuser.password': environment.get('MDBActivationSpecs', 'qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.InterchangeLoaderMDB.maxPoolDepth': '20',
    'com.clear2pay.opf.mdb.activationSpec.InterchangeLoaderMDB.hostName': environment.get('MDBActivationSpecs', 'qcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.InterchangeLoaderMDB.port': environment.get('MDBActivationSpecs', 'qcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.InterchangeLoaderMDB.channel': environment.get('MDBActivationSpecs', 'qcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.InterchangeLoaderMDB.transportType': environment.get('MDBActivationSpecs', 'qcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.InterchangeLoaderMDB.queueManager': environment.get('MDBActivationSpecs', 'qcf_queueManager'),
    'com.clear2pay.opf.mdb.activationSpec.HandoverInterchangeLoaderMDB.qcfuser.name': environment.get('MDBActivationSpecs', 'myqcf_qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.HandoverInterchangeLoaderMDB.qcfuser.password': environment.get('MDBActivationSpecs', 'myqcf_qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.HandoverInterchangeLoaderMDB.maxPoolDepth': '20',
    'com.clear2pay.opf.mdb.activationSpec.HandoverInterchangeLoaderMDB.hostName': environment.get('MDBActivationSpecs', 'myqcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.HandoverInterchangeLoaderMDB.port': environment.get('MDBActivationSpecs', 'myqcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.HandoverInterchangeLoaderMDB.channel': environment.get('MDBActivationSpecs', 'myqcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.HandoverInterchangeLoaderMDB.transportType': environment.get('MDBActivationSpecs', 'myqcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.HandoverInterchangeLoaderMDB.queueManager': environment.get('MDBActivationSpecs', 'myqcf_queueManager'),
    'com.clear2pay.opf.mdb.activationSpec.StagingServiceMDB.qcfuser.name': environment.get('MDBActivationSpecs', 'myqcf_qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.StagingServiceMDB.qcfuser.password': environment.get('MDBActivationSpecs', 'myqcf_qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.StagingServiceMDB.maxPoolDepth': '5',
    'com.clear2pay.opf.mdb.activationSpec.StagingServiceMDB.hostName': environment.get('MDBActivationSpecs', 'myqcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.StagingServiceMDB.port': environment.get('MDBActivationSpecs', 'myqcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.StagingServiceMDB.channel': environment.get('MDBActivationSpecs', 'myqcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.StagingServiceMDB.transportType': environment.get('MDBActivationSpecs', 'myqcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.StagingServiceMDB.queueManager': environment.get('MDBActivationSpecs', 'myqcf_queueManager'),
    'com.clear2pay.opf.mdb.activationSpec.StagingServiceUrgency1MDB.qcfuser.name': environment.get('MDBActivationSpecs', 'myqcf_qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.StagingServiceUrgency1MDB.qcfuser.password': environment.get('MDBActivationSpecs', 'myqcf_qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.StagingServiceUrgency1MDB.maxPoolDepth': '5',
    'com.clear2pay.opf.mdb.activationSpec.StagingServiceUrgency1MDB.hostName': environment.get('MDBActivationSpecs', 'myqcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.StagingServiceUrgency1MDB.port': environment.get('MDBActivationSpecs', 'myqcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.StagingServiceUrgency1MDB.channel': environment.get('MDBActivationSpecs', 'myqcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.StagingServiceUrgency1MDB.transportType': environment.get('MDBActivationSpecs', 'myqcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.StagingServiceUrgency1MDB.queueManager': environment.get('MDBActivationSpecs', 'myqcf_queueManager'),
    'com.clear2pay.opf.mdb.activationSpec.InterfacingReplyMDB.qcfuser.name': environment.get('MDBActivationSpecs', 'qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.InterfacingReplyMDB.qcfuser.password': environment.get('MDBActivationSpecs', 'qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.InterfacingReplyMDB.maxPoolDepth': '20',
    'com.clear2pay.opf.mdb.activationSpec.InterfacingReplyMDB.hostName': environment.get('MDBActivationSpecs', 'qcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.InterfacingReplyMDB.port': environment.get('MDBActivationSpecs', 'qcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.InterfacingReplyMDB.channel': environment.get('MDBActivationSpecs', 'qcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.InterfacingReplyMDB.transportType': environment.get('MDBActivationSpecs', 'qcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.InterfacingReplyMDB.queueManager': environment.get('MDBActivationSpecs', 'qcf_queueManager'),
    'com.clear2pay.opf.mdb.activationSpec.HandoverInterfacingReplyMDB.qcfuser.name': environment.get('MDBActivationSpecs', 'myqcf_qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.HandoverInterfacingReplyMDB.qcfuser.password': environment.get('MDBActivationSpecs', 'myqcf_qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.HandoverInterfacingReplyMDB.maxPoolDepth': '20',
    'com.clear2pay.opf.mdb.activationSpec.HandoverInterfacingReplyMDB.hostName': environment.get('MDBActivationSpecs', 'myqcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.HandoverInterfacingReplyMDB.port': environment.get('MDBActivationSpecs', 'myqcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.HandoverInterfacingReplyMDB.channel': environment.get('MDBActivationSpecs', 'myqcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.HandoverInterfacingReplyMDB.transportType': environment.get('MDBActivationSpecs', 'myqcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.HandoverInterfacingReplyMDB.queueManager': environment.get('MDBActivationSpecs', 'myqcf_queueManager'),
    'com.clear2pay.opf.mdb.activationSpec.InterfacingHeraldMDB.qcfuser.name': environment.get('MDBActivationSpecs', 'myqcf_qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.InterfacingHeraldMDB.qcfuser.password': environment.get('MDBActivationSpecs', 'myqcf_qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.InterfacingHeraldMDB.maxPoolDepth': '20',
    'com.clear2pay.opf.mdb.activationSpec.InterfacingHeraldMDB.hostName': environment.get('MDBActivationSpecs', 'myqcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.InterfacingHeraldMDB.port': environment.get('MDBActivationSpecs', 'myqcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.InterfacingHeraldMDB.channel': environment.get('MDBActivationSpecs', 'myqcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.InterfacingHeraldMDB.transportType': environment.get('MDBActivationSpecs', 'myqcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.InterfacingHeraldMDB.queueManager': environment.get('MDBActivationSpecs', 'myqcf_queueManager'),
    'com.clear2pay.opf.mdb.activationSpec.InterfacingRequestMDB.qcfuser.name': environment.get('MDBActivationSpecs', 'myqcf_qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.InterfacingRequestMDB.qcfuser.password': environment.get('MDBActivationSpecs', 'myqcf_qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.InterfacingRequestMDB.maxPoolDepth': '20',
    'com.clear2pay.opf.mdb.activationSpec.InterfacingRequestMDB.hostName': environment.get('MDBActivationSpecs', 'myqcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.InterfacingRequestMDB.port': environment.get('MDBActivationSpecs', 'myqcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.InterfacingRequestMDB.channel': environment.get('MDBActivationSpecs', 'myqcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.InterfacingRequestMDB.transportType': environment.get('MDBActivationSpecs', 'myqcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.InterfacingRequestMDB.queueManager': environment.get('MDBActivationSpecs', 'myqcf_queueManager'),
    'com.clear2pay.opf.mdb.activationSpec.RestSubmissionMDB.qcfuser.name': environment.get('MDBActivationSpecs', 'myqcf_qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.RestSubmissionMDB.qcfuser.password': environment.get('MDBActivationSpecs', 'myqcf_qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.RestSubmissionMDB.maxPoolDepth': '20',
    'com.clear2pay.opf.mdb.activationSpec.RestSubmissionMDB.hostName': environment.get('MDBActivationSpecs', 'myqcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.RestSubmissionMDB.port': environment.get('MDBActivationSpecs', 'myqcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.RestSubmissionMDB.channel': environment.get('MDBActivationSpecs', 'myqcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.RestSubmissionMDB.transportType': environment.get('MDBActivationSpecs', 'myqcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.RestSubmissionMDB.queueManager': environment.get('MDBActivationSpecs', 'myqcf_queueManager'),
    'com.clear2pay.opf.mdb.activationSpec.SWIFTSAAInterchangeLoaderMDB.qcfuser.name': environment.get('MDBActivationSpecs', 'swiftsaaqcf_qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.SWIFTSAAInterchangeLoaderMDB.qcfuser.password': environment.get('MDBActivationSpecs', 'swiftsaaqcf_qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.SWIFTSAAInterchangeLoaderMDB.maxPoolDepth': '5',
    'com.clear2pay.opf.mdb.activationSpec.SWIFTSAAInterchangeLoaderMDB.hostName': environment.get('MDBActivationSpecs', 'swiftsaaqcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.SWIFTSAAInterchangeLoaderMDB.port': environment.get('MDBActivationSpecs', 'swiftsaaqcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.SWIFTSAAInterchangeLoaderMDB.channel': environment.get('MDBActivationSpecs', 'swiftsaaqcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.SWIFTSAAInterchangeLoaderMDB.transportType': environment.get('MDBActivationSpecs', 'swiftsaaqcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.SWIFTSAAInterchangeLoaderMDB.queueManager': environment.get('MDBActivationSpecs', 'swiftsaaqcf_queueManager'),
    'com.clear2pay.opf.mdb.activationSpec.HandoverSWIFTSAAInterchangeLoaderMDB.qcfuser.name': environment.get('MDBActivationSpecs', 'myqcf_qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.HandoverSWIFTSAAInterchangeLoaderMDB.qcfuser.password': environment.get('MDBActivationSpecs', 'myqcf_qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.HandoverSWIFTSAAInterchangeLoaderMDB.maxPoolDepth': '5',
    'com.clear2pay.opf.mdb.activationSpec.HandoverSWIFTSAAInterchangeLoaderMDB.hostName': environment.get('MDBActivationSpecs', 'myqcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.HandoverSWIFTSAAInterchangeLoaderMDB.port': environment.get('MDBActivationSpecs', 'myqcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.HandoverSWIFTSAAInterchangeLoaderMDB.channel': environment.get('MDBActivationSpecs', 'myqcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.HandoverSWIFTSAAInterchangeLoaderMDB.transportType': environment.get('MDBActivationSpecs', 'myqcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.HandoverSWIFTSAAInterchangeLoaderMDB.queueManager': environment.get('MDBActivationSpecs', 'myqcf_queueManager'),

    #StandingOrder MDBs
    'com.clear2pay.opf.mdb.activationSpec.SOInitiationMDB.qcfuser.name': environment.get('MDBActivationSpecs', 'qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.SOInitiationMDB.qcfuser.password': environment.get('MDBActivationSpecs', 'qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.SOInitiationMDB.maxPoolDepth': '5',
    'com.clear2pay.opf.mdb.activationSpec.SOInitiationMDB.hostName': environment.get('MDBActivationSpecs', 'qcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.SOInitiationMDB.port': environment.get('MDBActivationSpecs', 'qcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.SOInitiationMDB.channel': environment.get('MDBActivationSpecs', 'qcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.SOInitiationMDB.transportType': environment.get('MDBActivationSpecs', 'qcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.SOInitiationMDB.queueManager': environment.get('MDBActivationSpecs', 'qcf_queueManager'),
    
    #CORAL MDBs
    'com.clear2pay.opf.mdb.activationSpec.BOEBackOfficeMDB.qcfuser.name': environment.get('MDBActivationSpecs', 'qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.BOEBackOfficeMDB.qcfuser.password': environment.get('MDBActivationSpecs', 'qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.BOEBackOfficeMDB.maxPoolDepth': '5',
    'com.clear2pay.opf.mdb.activationSpec.BOEBackOfficeMDB.hostName': environment.get('MDBActivationSpecs', 'qcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.BOEBackOfficeMDB.port': environment.get('MDBActivationSpecs', 'qcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.BOEBackOfficeMDB.channel': environment.get('MDBActivationSpecs', 'qcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.BOEBackOfficeMDB.transportType': environment.get('MDBActivationSpecs', 'qcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.BOEBackOfficeMDB.queueManager': environment.get('MDBActivationSpecs', 'qcf_queueManager'),
    'com.clear2pay.opf.mdb.activationSpec.Urgency8InterchangeLoaderMDB.qcfuser.name': environment.get('MDBActivationSpecs', 'qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.Urgency8InterchangeLoaderMDB.qcfuser.password': environment.get('MDBActivationSpecs', 'qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.Urgency8InterchangeLoaderMDB.maxPoolDepth': '5',
    'com.clear2pay.opf.mdb.activationSpec.Urgency8InterchangeLoaderMDB.hostName': environment.get('MDBActivationSpecs', 'qcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.Urgency8InterchangeLoaderMDB.port': environment.get('MDBActivationSpecs', 'qcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.Urgency8InterchangeLoaderMDB.channel': environment.get('MDBActivationSpecs', 'qcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.Urgency8InterchangeLoaderMDB.transportType': environment.get('MDBActivationSpecs', 'qcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.Urgency8InterchangeLoaderMDB.queueManager': environment.get('MDBActivationSpecs', 'qcf_queueManager'),
    'com.clear2pay.opf.mdb.activationSpec.Urgency8ParsingServiceMDB.qcfuser.name': environment.get('MDBActivationSpecs', 'qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.Urgency8ParsingServiceMDB.qcfuser.password': environment.get('MDBActivationSpecs', 'qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.Urgency8ParsingServiceMDB.maxPoolDepth': '5',
    'com.clear2pay.opf.mdb.activationSpec.Urgency8ParsingServiceMDB.hostName': environment.get('MDBActivationSpecs', 'qcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.Urgency8ParsingServiceMDB.port': environment.get('MDBActivationSpecs', 'qcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.Urgency8ParsingServiceMDB.channel': environment.get('MDBActivationSpecs', 'qcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.Urgency8ParsingServiceMDB.transportType': environment.get('MDBActivationSpecs', 'qcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.Urgency8ParsingServiceMDB.queueManager': environment.get('MDBActivationSpecs', 'qcf_queueManager'),
    'com.clear2pay.opf.mdb.activationSpec.Urgency8AsyncBPELInvoker.qcfuser.name': environment.get('MDBActivationSpecs', 'qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.Urgency8AsyncBPELInvoker.qcfuser.password': environment.get('MDBActivationSpecs', 'qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.Urgency8AsyncBPELInvoker.maxPoolDepth': '5',
    'com.clear2pay.opf.mdb.activationSpec.Urgency8AsyncBPELInvoker.hostName': environment.get('MDBActivationSpecs', 'qcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.Urgency8AsyncBPELInvoker.port': environment.get('MDBActivationSpecs', 'qcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.Urgency8AsyncBPELInvoker.channel': environment.get('MDBActivationSpecs', 'qcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.Urgency8AsyncBPELInvoker.transportType': environment.get('MDBActivationSpecs', 'qcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.Urgency8AsyncBPELInvoker.queueManager': environment.get('MDBActivationSpecs', 'qcf_queueManager'),
    'com.clear2pay.opf.mdb.activationSpec.TransportReceiptMDB.qcfuser.name': environment.get('MDBActivationSpecs', 'qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.TransportReceiptMDB.qcfuser.password': environment.get('MDBActivationSpecs', 'qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.TransportReceiptMDB.maxPoolDepth': '5',
    'com.clear2pay.opf.mdb.activationSpec.TransportReceiptMDB.hostName': environment.get('MDBActivationSpecs', 'qcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.TransportReceiptMDB.port': environment.get('MDBActivationSpecs', 'qcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.TransportReceiptMDB.channel': environment.get('MDBActivationSpecs', 'qcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.TransportReceiptMDB.transportType': environment.get('MDBActivationSpecs', 'qcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.TransportReceiptMDB.queueManager': environment.get('MDBActivationSpecs', 'qcf_queueManager'),
    'com.clear2pay.opf.mdb.activationSpec.DummyTechExceptionTesterMDB.qcfuser.name': environment.get('MDBActivationSpecs', 'qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.DummyTechExceptionTesterMDB.qcfuser.password': environment.get('MDBActivationSpecs', 'qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.DummyTechExceptionTesterMDB.maxPoolDepth': '5',
    'com.clear2pay.opf.mdb.activationSpec.DummyTechExceptionTesterMDB.hostName': environment.get('MDBActivationSpecs', 'qcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.DummyTechExceptionTesterMDB.port': environment.get('MDBActivationSpecs', 'qcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.DummyTechExceptionTesterMDB.channel': environment.get('MDBActivationSpecs', 'qcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.DummyTechExceptionTesterMDB.transportType': environment.get('MDBActivationSpecs', 'qcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.DummyTechExceptionTesterMDB.queueManager': environment.get('MDBActivationSpecs', 'qcf_queueManager'),
    'com.clear2pay.opf.mdb.activationSpec.STETMDB.qcfuser.name': environment.get('MDBActivationSpecs', 'qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.STETMDB.qcfuser.password': environment.get('MDBActivationSpecs', 'qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.STETMDB.maxPoolDepth': '5',
    'com.clear2pay.opf.mdb.activationSpec.STETMDB.hostName': environment.get('MDBActivationSpecs', 'qcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.STETMDB.port': environment.get('MDBActivationSpecs', 'qcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.STETMDB.channel': environment.get('MDBActivationSpecs', 'qcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.STETMDB.transportType': environment.get('MDBActivationSpecs', 'qcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.STETMDB.queueManager': environment.get('MDBActivationSpecs', 'qcf_queueManager'),
    'com.clear2pay.opf.mdb.activationSpec.LBInterchangeLoaderMDB.qcfuser.name': environment.get('MDBActivationSpecs', 'qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.LBInterchangeLoaderMDB.qcfuser.password': environment.get('MDBActivationSpecs', 'qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.LBInterchangeLoaderMDB.maxPoolDepth': '5',
    'com.clear2pay.opf.mdb.activationSpec.LBInterchangeLoaderMDB.hostName': environment.get('MDBActivationSpecs', 'qcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.LBInterchangeLoaderMDB.port': environment.get('MDBActivationSpecs', 'qcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.LBInterchangeLoaderMDB.channel': environment.get('MDBActivationSpecs', 'qcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.LBInterchangeLoaderMDB.transportType': environment.get('MDBActivationSpecs', 'qcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.LBInterchangeLoaderMDB.queueManager': environment.get('MDBActivationSpecs', 'qcf_queueManager'),
    'com.clear2pay.opf.mdb.activationSpec.SWIFTAGIInterchangeLoaderMDB.qcfuser.name': environment.get('MDBActivationSpecs', 'qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.SWIFTAGIInterchangeLoaderMDB.qcfuser.password': environment.get('MDBActivationSpecs', 'qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.SWIFTAGIInterchangeLoaderMDB.maxPoolDepth': '5',
    'com.clear2pay.opf.mdb.activationSpec.SWIFTAGIInterchangeLoaderMDB.hostName': environment.get('MDBActivationSpecs', 'qcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.SWIFTAGIInterchangeLoaderMDB.port': environment.get('MDBActivationSpecs', 'qcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.SWIFTAGIInterchangeLoaderMDB.channel': environment.get('MDBActivationSpecs', 'qcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.SWIFTAGIInterchangeLoaderMDB.transportType': environment.get('MDBActivationSpecs', 'qcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.SWIFTAGIInterchangeLoaderMDB.queueManager': environment.get('MDBActivationSpecs', 'qcf_queueManager'),
    'com.clear2pay.opf.mdb.activationSpec.SWIFTAGIAckInterchangeLoaderMDB.qcfuser.name': environment.get('MDBActivationSpecs', 'qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.SWIFTAGIAckInterchangeLoaderMDB.qcfuser.password': environment.get('MDBActivationSpecs', 'qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.SWIFTAGIAckInterchangeLoaderMDB.maxPoolDepth': '5',
    'com.clear2pay.opf.mdb.activationSpec.SWIFTAGIAckInterchangeLoaderMDB.hostName': environment.get('MDBActivationSpecs', 'qcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.SWIFTAGIAckInterchangeLoaderMDB.port': environment.get('MDBActivationSpecs', 'qcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.SWIFTAGIAckInterchangeLoaderMDB.channel': environment.get('MDBActivationSpecs', 'qcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.SWIFTAGIAckInterchangeLoaderMDB.transportType': environment.get('MDBActivationSpecs', 'qcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.SWIFTAGIAckInterchangeLoaderMDB.queueManager': environment.get('MDBActivationSpecs', 'qcf_queueManager'),
    'com.clear2pay.opf.mdb.activationSpec.SWIFTSAAInterchangeLoaderMDB.qcfuser.name': environment.get('MDBActivationSpecs', 'qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.SWIFTSAAInterchangeLoaderMDB.qcfuser.password': environment.get('MDBActivationSpecs', 'qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.SWIFTSAAInterchangeLoaderMDB.maxPoolDepth': '5',
    'com.clear2pay.opf.mdb.activationSpec.SWIFTSAAInterchangeLoaderMDB.hostName': environment.get('MDBActivationSpecs', 'qcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.SWIFTSAAInterchangeLoaderMDB.port': environment.get('MDBActivationSpecs', 'qcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.SWIFTSAAInterchangeLoaderMDB.channel': environment.get('MDBActivationSpecs', 'qcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.SWIFTSAAInterchangeLoaderMDB.transportType': environment.get('MDBActivationSpecs', 'qcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.SWIFTSAAInterchangeLoaderMDB.queueManager': environment.get('MDBActivationSpecs', 'qcf_queueManager'),
    'com.clear2pay.opf.mdb.activationSpec.HandoverSWIFTSAAInterchangeLoaderMDB.qcfuser.name': environment.get('MDBActivationSpecs', 'qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.HandoverSWIFTSAAInterchangeLoaderMDB.qcfuser.password': environment.get('MDBActivationSpecs', 'myqcf_qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.HandoverSWIFTSAAInterchangeLoaderMDB.maxPoolDepth': '20',
    'com.clear2pay.opf.mdb.activationSpec.HandoverSWIFTSAAInterchangeLoaderMDB.hostName': environment.get('MDBActivationSpecs', 'myqcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.HandoverSWIFTSAAInterchangeLoaderMDB.port': environment.get('MDBActivationSpecs', 'myqcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.HandoverSWIFTSAAInterchangeLoaderMDB.channel': environment.get('MDBActivationSpecs', 'myqcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.HandoverSWIFTSAAInterchangeLoaderMDB.transportType': environment.get('MDBActivationSpecs', 'myqcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.HandoverSWIFTSAAInterchangeLoaderMDB.queueManager': environment.get('MDBActivationSpecs', 'myqcf_queueManager'),

    #PlatformTest Services MDBs
    'com.clear2pay.opf.mdb.activationSpec.MessagingMDB.qcfuser.name': environment.get('MDBActivationSpecs', 'qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.MessagingMDB.qcfuser.password': environment.get('MDBActivationSpecs', 'qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.MessagingMDB.maxPoolDepth': '5',
    'com.clear2pay.opf.mdb.activationSpec.MessagingMDB.hostName': environment.get('MDBActivationSpecs', 'qcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.MessagingMDB.port': environment.get('MDBActivationSpecs', 'qcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.MessagingMDB.channel': environment.get('MDBActivationSpecs', 'qcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.MessagingMDB.transportType': environment.get('MDBActivationSpecs', 'qcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.MessagingMDB.queueManager': environment.get('MDBActivationSpecs', 'qcf_queueManager'),
    'com.clear2pay.opf.mdb.activationSpec.Ejb2MessagingMDB.qcfuser.name': environment.get('MDBActivationSpecs', 'qcfuser_name'),
    'com.clear2pay.opf.mdb.activationSpec.Ejb2MessagingMDB.qcfuser.password': environment.get('MDBActivationSpecs', 'qcfuser_password'),
    'com.clear2pay.opf.mdb.activationSpec.Ejb2MessagingMDB.maxPoolDepth': '5',
    'com.clear2pay.opf.mdb.activationSpec.Ejb2MessagingMDB.hostName': environment.get('MDBActivationSpecs', 'qcf_hostName'),
    'com.clear2pay.opf.mdb.activationSpec.Ejb2MessagingMDB.port': environment.get('MDBActivationSpecs', 'qcf_port'),
    'com.clear2pay.opf.mdb.activationSpec.Ejb2MessagingMDB.channel': environment.get('MDBActivationSpecs', 'qcf_channel'),
    'com.clear2pay.opf.mdb.activationSpec.Ejb2MessagingMDB.transportType': environment.get('MDBActivationSpecs', 'qcf_transportType'),
    'com.clear2pay.opf.mdb.activationSpec.Ejb2MessagingMDB.queueManager': environment.get('MDBActivationSpecs', 'qcf_queueManager')
}
cli.cd('/')
for key in sys_props:
    cli.recreate('./system-property=%s' % key, {'value': sys_props[key]})

cli.disconnect()
